// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCNNjT-vJjEAjILa86bWIncN_9taiuBRR8',
    appId: '1:741773027341:web:8640e9616e5534469e0d44',
    messagingSenderId: '741773027341',
    projectId: 'mobil-cihazlar',
    authDomain: 'mobil-cihazlar.firebaseapp.com',
    storageBucket: 'mobil-cihazlar.appspot.com',
    measurementId: 'G-LM110DZ7M5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDtZumjuN6YEJhEQECLYu1q85QpRIhI5Mo',
    appId: '1:741773027341:android:9cfe8fddf9b42c669e0d44',
    messagingSenderId: '741773027341',
    projectId: 'mobil-cihazlar',
    storageBucket: 'mobil-cihazlar.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBelIIlupDRwrw8PYtCr5pfZqibDlHFIGw',
    appId: '1:741773027341:ios:5c0ae6797a189bc19e0d44',
    messagingSenderId: '741773027341',
    projectId: 'mobil-cihazlar',
    storageBucket: 'mobil-cihazlar.appspot.com',
    iosBundleId: 'com.example.vizeOdev',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBelIIlupDRwrw8PYtCr5pfZqibDlHFIGw',
    appId: '1:741773027341:ios:9832ac8186b022a89e0d44',
    messagingSenderId: '741773027341',
    projectId: 'mobil-cihazlar',
    storageBucket: 'mobil-cihazlar.appspot.com',
    iosBundleId: 'com.example.vizeOdev.RunnerTests',
  );
}
